package ch.ehi.ili2ofgdb.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLClientInfoException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import ch.ehi.openfgdb4j.OpenFgdb;
import ch.ehi.openfgdb4j.OpenFgdbException;

public class OfgdbConnection implements Connection {
    private final OpenFgdb api;
    private final String url;
    private final LinkedHashSet<String> knownTables = new LinkedHashSet<String>();
    private long dbHandle;
    private boolean closed = false;

    protected OfgdbConnection(OpenFgdb api, long dbHandle, String url) {
        this.api = api;
        this.dbHandle = dbHandle;
        this.url = url;
        try {
            for (String tableName : api.listTableNames(dbHandle)) {
                registerTableName(tableName);
            }
        } catch (OpenFgdbException ignore) {
            // Metadata bootstrap should not block connection creation.
        }
    }

    OpenFgdb getApi() {
        return api;
    }

    long getDbHandle() {
        return dbHandle;
    }

    public OpenFgdb getOpenFgdbApi() throws SQLException {
        ensureOpen();
        return api;
    }

    public long getOpenFgdbHandle() throws SQLException {
        ensureOpen();
        return dbHandle;
    }

    String getUrl() {
        return url;
    }

    void registerTableName(String tableName) {
        if (tableName != null && !tableName.isEmpty()) {
            knownTables.add(tableName);
        }
    }

    void removeTableName(String tableName) {
        if (tableName != null) {
            knownTables.remove(tableName);
        }
    }

    java.util.List<String> getKnownTableNames() {
        return new ArrayList<String>(knownTables);
    }

    @Override
    public Statement createStatement() throws SQLException {
        ensureOpen();
        return new OfgdbStatement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        ensureOpen();
        return new OfgdbPreparedStatement(this, sql);
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        ensureOpen();
        return new OfgdbMetaData(this);
    }

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        try {
            api.close(dbHandle);
            dbHandle = 0L;
            closed = true;
        } catch (OpenFgdbException e) {
            throw new SQLException("failed to close openfgdb connection", e);
        }
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public void commit() {
    }

    @Override
    public void rollback() {
    }

    @Override
    public void rollback(Savepoint savepoint) {
    }

    @Override
    public void setAutoCommit(boolean autoCommit) {
    }

    @Override
    public boolean getAutoCommit() {
        return true;
    }

    @Override
    public String nativeSQL(String sql) {
        return sql;
    }

    @Override
    public void clearWarnings() {
    }

    @Override
    public SQLWarning getWarnings() {
        return null;
    }

    @Override
    public String getCatalog() {
        return null;
    }

    @Override
    public void setCatalog(String catalog) {
    }

    @Override
    public int getTransactionIsolation() {
        return Connection.TRANSACTION_NONE;
    }

    @Override
    public void setTransactionIsolation(int level) {
    }

    @Override
    public boolean isReadOnly() {
        return false;
    }

    @Override
    public void setReadOnly(boolean readOnly) {
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public Savepoint setSavepoint() {
        return null;
    }

    @Override
    public Savepoint setSavepoint(String name) {
        return null;
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) {
    }

    @Override
    public int getHoldability() {
        return 0;
    }

    @Override
    public void setHoldability(int holdability) {
    }

    @Override
    public Map<String, Class<?>> getTypeMap() {
        return null;
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) {
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public boolean isValid(int timeout) {
        return !closed;
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
    }

    @Override
    public String getClientInfo(String name) {
        return null;
    }

    @Override
    public Properties getClientInfo() {
        return new Properties();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new SQLException("Not supported");
    }

    @Override
    public String getSchema() {
        return null;
    }

    @Override
    public void setSchema(String schema) {
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        close();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) {
    }

    @Override
    public int getNetworkTimeout() {
        return 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface == null) {
            throw new SQLException("iface is null");
        }
        if (iface.isAssignableFrom(getClass())) {
            return iface.cast(this);
        }
        if (iface.isAssignableFrom(OpenFgdb.class)) {
            ensureOpen();
            return iface.cast(api);
        }
        throw new SQLException("not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        if (iface == null) {
            return false;
        }
        return iface.isAssignableFrom(getClass()) || iface.isAssignableFrom(OpenFgdb.class);
    }

    private void ensureOpen() throws SQLException {
        if (closed) {
            throw new SQLException("connection is closed");
        }
    }
}
